toerh client/config/routes.rb
require 'api_constraints'

TOERH::Application.routes.draw do

  match '/*path' => 'sessions#home', :via => :options

  get '', to: 'sessions#home'
  
  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  get '/authenticate' => 'sessions#authenticate'

  namespace :api, defaults: {format: 'json'}, :provides => [:json, :xml] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :resources
      resources :users
      resources :tags
      resources :types
      resources :licenses

      get 'tags/:id/resources', to: 'tags#resources', as: 'rtag'
      get 'types/:id/resources', to: 'types#resources', as: 'rresourcetype'
      get 'licenses/:id/resources', to: 'licenses#resources', as: 'rlicense'
      get 'users/:id/resources', to: 'users#resources', as: 'ruser'
    end

    match '*rest', to: 'base#notfound', via: :all
  end

  namespace :dev do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      get '', to: 'apiusers#login'

      get 'register', to: 'apiusers#register'
      get 'account', to: 'apiusers#account', as: 'account'
      post 'register', to: 'apiusers#create', as: 'apiusers'
      get 'login', to: 'apiusers#login'
      post 'login', to: 'apiusers#post_login', as: 'post_login'
      get 'logout', to: 'apiusers#logout', as: 'logout'

      get 'users', to: 'apiusers#users', as: 'userslist'
      get 'users/:id/edit', to: 'apiusers#edit', as: 'edit_user'
      patch 'users/:id/edit', to: 'apiusers#update', as: 'update_user'
      delete 'users/:id/delete', to: 'apiusers#destroy', as: 'delete_user'

      get 'docs' => 'docs#index'
      get 'docs/getting-started' => 'docs#index', as: 'start'
      get 'docs/resources' => 'docs#resources', as: 'resources'
      get 'docs/users' => 'docs#users', as: 'users'
      get 'docs/tags' => 'docs#tags', as: 'tags'
      get 'docs/licenses' => 'docs#licenses', as: 'licenses'
      get 'docs/resource-types' => 'docs#resourcetypes', as: 'resourcetypes'
      get 'docs/errors' => 'docs#errors', as: 'errors'
    end
  end

  match '*rest', to: 'application#notfound', via: :all

end

toerh client/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Toerh documentation</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <%= stylesheet_link_tag "normalize", "style" %>

        <%= javascript_include_tag "application" %>

    </head>
    <body>

        <div class="header-band">
            <div class="header">
                <div class="logo">Toerh developers</div>

                <div class="nav">
                    <ul>
                        <li><%= link_to 'Documentation', dev_docs_path() %></li>
                        <% if current_admin.present? %>
                            <li><%= link_to 'Users', dev_userslist_path() %></li>
                        <% end %>
                        <% if current_user.present? %>
                            <li><%= link_to 'Dashboard', dev_account_path() %></li>
                            <li><%= link_to 'Logout', dev_logout_path() %></li>
                        <% else %>
                            <li><%= link_to 'Login', dev_login_path() %></li>
                            <li><%= link_to 'Register', dev_register_path() %></li>
                        <% end %>
                    </ul>
                </div>

            </div>
        </div>

        <div class="main-container">

            <%= yield :main %>
            
        </div>

    </body>
</html>

toerh client/app/views/layouts/docs.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Toerh documentation</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <%= stylesheet_link_tag "normalize", "style" %>

    </head>
    <body>

        <div class="header-band">
            <div class="header">
                <div class="logo">Toerh documentaion</div>
            
                <div class="nav">
                    <ul>
                        <li><%= link_to 'Documentation', dev_docs_path() %></li>
                        <% if current_admin.present? %>
                            <li><%= link_to 'Users', dev_userslist_path() %></li>
                        <% end %>
                        <% if current_user.present? %>
                            <li><%= link_to 'Dashboard', dev_account_path() %></li>
                            <li><%= link_to 'Logout', dev_logout_path() %></li>
                        <% else %>
                            <li><%= link_to 'Login', dev_login_path() %></li>
                            <li><%= link_to 'Register', dev_register_path() %></li>
                        <% end %>
                    </ul>
                </div>

            </div>
        </div>

        <div class="container">
            <div class="sidebar">
                <ul>
                    <li><%= link_to 'Getting started', dev_start_path() %></li>
                    <li><%= link_to 'Resources', dev_resources_path() %></li>
                    <li><%= link_to 'Users', dev_users_path() %></li>
                    <li><%= link_to 'Tags', dev_tags_path() %></li>
                    <li><%= link_to 'Licenses', dev_licenses_path() %></li>
                    <li><%= link_to 'Resource types', dev_resourcetypes_path() %></li>
                    <li><%= link_to 'Errors', dev_errors_path() %></li>
                </ul>
            </div>

            <div class="main">

                <%= yield :main %>

            </div>
            
        </div>

    </body>
</html>

toerh client/app/views/layouts/home.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Toerh documentation</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <%= stylesheet_link_tag "normalize", "style" %>

        <%= javascript_include_tag "application" %>

    </head>
    <body>

        <div class="header-band">
            <div class="header">
                <div class="logo">Toerh developers</div>

                <div class="nav">
                    <ul>
                        <li><%= link_to 'Documentation', dev_docs_path() %></li>
                        <li><%= link_to 'Login', dev_login_path() %></li>
                        <li><%= link_to 'Register', dev_register_path() %></li>
                    </ul>
                </div>

            </div>
        </div>

        <div class="main-container">

            <%= yield :main %>
            
        </div>

    </body>
</html>