toerh client/config/routes.rb
require 'api_constraints'

TOERH::Application.routes.draw do

  match '/*path' => 'sessions#home', :via => :options

  get '', to: 'sessions#home'
  
  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  get '/authenticate' => 'sessions#authenticate'

  namespace :api, defaults: {format: 'json'}, :provides => [:json, :xml] do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :resources
      resources :users
      resources :tags
      resources :types
      resources :licenses

      get 'tags/:id/resources', to: 'tags#resources', as: 'rtag'
      get 'types/:id/resources', to: 'types#resources', as: 'rresourcetype'
      get 'licenses/:id/resources', to: 'licenses#resources', as: 'rlicense'
      get 'users/:id/resources', to: 'users#resources', as: 'ruser'
    end

    match '*rest', to: 'base#notfound', via: :all
  end

  namespace :dev do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      get '', to: 'apiusers#login'

      get 'register', to: 'apiusers#register'
      get 'account', to: 'apiusers#account', as: 'account'
      post 'register', to: 'apiusers#create', as: 'apiusers'
      get 'login', to: 'apiusers#login'
      post 'login', to: 'apiusers#post_login', as: 'post_login'
      get 'logout', to: 'apiusers#logout', as: 'logout'

      get 'users', to: 'apiusers#users', as: 'userslist'
      get 'users/:id/edit', to: 'apiusers#edit', as: 'edit_user'
      patch 'users/:id/edit', to: 'apiusers#update', as: 'update_user'
      delete 'users/:id/delete', to: 'apiusers#destroy', as: 'delete_user'

      get 'docs' => 'docs#index'
      get 'docs/getting-started' => 'docs#index', as: 'start'
      get 'docs/resources' => 'docs#resources', as: 'resources'
      get 'docs/users' => 'docs#users', as: 'users'
      get 'docs/tags' => 'docs#tags', as: 'tags'
      get 'docs/licenses' => 'docs#licenses', as: 'licenses'
      get 'docs/resource-types' => 'docs#resourcetypes', as: 'resourcetypes'
      get 'docs/errors' => 'docs#errors', as: 'errors'
    end
  end

  match '*rest', to: 'application#notfound', via: :all

end

toerh client/app/models/apiuser.rb
class Apiuser < ActiveRecord::Base
	has_secure_password
	before_create :generate_access_token

	validates :email, presence: true,
						:uniqueness => true,
						:format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
	validates :password, :presence => true,
                       	:confirmation => true,
                       	:length => {:within => 6..40},
                       	:on => :create

	private
		def generate_access_token
			begin
				self.access_token = SecureRandom.hex
			end while self.class.exists?(access_token: access_token)
		end

	def self.find_and_increment(conditions = :none)
	  	if object = where(conditions).first
	    	object.increment!(:count)
	  	end
	end
end

toerh client/app/controllers/api/v1/licenses_controller.rb
module Api
	module V1
		class LicensesController < BaseController
			before_filter :restrict_access_token

			respond_to :xml, :json

			def index
				if params[:limit]
					@licenses = License.page(params[:page]).per(params[:limit])
				else
					@licenses = License.page(params[:page])
				end
			end

			def show
        		@license = License.find(params[:id])

        		rescue
        			error(404, 404, 'The resource could not be found')
      		end

      		def resources
				@resources = License.find_by_id(params[:id]).resources

				if params[:limit]
					@resources = @resources.page(params[:page]).per(params[:limit])
				else
					@resources = @resources.page(params[:page])
				end

        		rescue
        			render_404
			end

		    private
			    def render_404
	  				error(404, 404, 'The user could not be found')
				end
		end
	end
end

toerh client/app/controllers/api/v1/resources_controller.rb
module Api
	module V1
		class ResourcesController < BaseController
			before_filter :restrict_access_login, :only => [:create, :update, :destroy]
			before_filter :restrict_access_token

			respond_to :xml, :json

			def cors
			end

			def index
				if params[:limit]
					@resources = Resource.page(params[:page]).per(params[:limit])
				else
					@resources = Resource.page(params[:page])
				end
			end

			def show
        		@resource = Resource.find(params[:id])

        		rescue
        			error(404, 404, 'Resursen hittades inte')
      		end

      		def create
        		@resource = Resource.new(resource_params)

        		if @resource.save
        		else
        			validation_error(@resource.errors.messages) and return
        		end

        		if(params.has_key?(:tags))
        			tags = params[:tags].to_s.split(",").map(&:to_i)

        			for tag in tags
					  	@tagging = Tagging.create(:resource_id => @resource.id, :tag_id => tag)
						@tagging.save
					end
        		end

        		respond_with @resource, status: 201

        		rescue
        			error(500, 500, 'Ett oväntat fel inträffade')
		    end

		    def update
		    	resource = Resource.find_by_id(params[:id])
		    	
		    	if resource.user_id != current_user.id
		    		error(403, 403, 'The resource belongs to another user') and return
		    	end

		    	if(params.has_key?(:tags))
			    	Tagging.destroy_all(:resource_id => resource.id)
			     	tags = params[:tags].to_s.split(",").map(&:to_i)

					for tag in tags
					  	@tagging = Tagging.create(:resource_id => resource.id, :tag_id => tag)
						@tagging.save
					end
				end

		        if resource.update(resource_params)
        		else
        			validation_error(resource.errors.messages) and return
        		end

		        respond_with @resource, status: 204

		    	rescue
		    		render_404
		    end

		    def destroy

		    	resource = Resource.find_by_id(params[:id])
		    	
		    	if resource.user_id != current_user.id
		    		error(403, 403, 'The resource belongs to another user') and return
		    	end

		        respond_with Resource.destroy(params[:id])
		        rescue
		    		render_404
		    end

		    private
			    def render_404
	  				error(404, 404, 'The resource could not be found')
				end

			private
			    def validation_error(message)
	  				error(422, 422, message)
				end

		    private
		  		def resource_params
		  			user = User.find_by_auth_token(request.headers['HTTP_X_AUTH_TOKEN'])
		  			params[:user_id] = user.id
		        	params.permit(:name, :description, :url, :license_id, :resource_type_id, :user_id)
		      	end
		end
	end
end

toerh client/app/controllers/api/v1/tags_controller.rb
module Api
	module V1
		class TagsController < BaseController
			before_filter :restrict_access_token

			respond_to :xml, :json

			def index
				if params[:limit]
					@tags = Tag.page(params[:page]).per(params[:limit])
				else
					@tags = Tag.page(params[:page])
				end
			end

			def show
        		@tag = Tag.find(params[:id])

        		rescue
        			error(404, 404, 'Resursen hittades inte')
      		end

      		def resources
				@resources = Tag.find_by_id(params[:id]).resources

				if params[:limit]
					@resources = @resources.page(params[:page]).per(params[:limit])
				else
					@resources = @resources.page(params[:page])
				end

        		rescue
        			render_404
			end

		    private
			    def render_404
	  				error(404, 404, 'The user could not be found')
				end
		end
	end
end

toerh client/app/controllers/api/v1/types_controller.rb
module Api
	module V1
		class TypesController < BaseController
			before_filter :restrict_access_token

			respond_to :xml, :json

			def index
				if params[:limit]
					@types = ResourceType.page(params[:page]).per(params[:limit])
				else
					@types = ResourceType.page(params[:page])
				end
			end

			def show
        		@type = ResourceType.find(params[:id])

        		rescue
        			error(404, 404, 'Resursen hittades inte')
      		end

      		def resources
				@resources = ResourceType.find_by_id(params[:id]).resources

				if params[:limit]
					@resources = @resources.page(params[:page]).per(params[:limit])
				else
					@resources = @resources.page(params[:page])
				end

        		rescue
        			render_404
			end

		    private
			    def render_404
	  				error(404, 404, 'The user could not be found')
				end
		end
	end
end

toerh client/app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < BaseController
			before_filter :restrict_access_token

			respond_to :xml, :json

			def index
				if params[:limit]
					@users = User.page(params[:page]).per(params[:limit])
				else
					@users = User.page(params[:page])
				end
			end

			def show
        		@user = User.find(params[:id])

        		rescue
        			error(404, 404, 'Resursen hittades inte')
      		end

      		def resources
				@resources = User.find_by_id(params[:id]).resources

				if params[:limit]
					@resources = @resources.page(params[:page]).per(params[:limit])
				else
					@resources = @resources.page(params[:page])
				end

        		rescue
        			render_404
			end

		    private
			    def render_404
	  				error(404, 404, 'The user could not be found')
				end
		end
	end
end

toerh client/app/controllers/dev/v1/apiusers_controller.rb
module Dev
	module V1
		class ApiusersController < BaseController
			before_action :require_login, only: [:account]
			before_action :require_admin, only: [:users]

			before_action :default_format_html

			layout "application"

			def login
			end

			def account
				apiuser = current_user
				@token = apiuser.access_token
				@email = apiuser.email
				@name = apiuser.name
				@count = apiuser.count
			end

			def register
				@apiuser = Apiuser.new
			end

			def create
				@apiuser = Apiuser.new(apiuser_params)
				if @apiuser.save
					session[:apiuser_id] = @apiuser.id
					redirect_to dev_account_path
				else
					render 'register'
				end
			end

			def post_login
				apiuser = Apiuser.find_by_email(params[:email])
				if apiuser && apiuser.authenticate(params[:password])
			    	session[:apiuser_id] = apiuser.id
			    	redirect_to dev_account_path
			  	else
			  		flash[:notice] = "Invalid email or password"
			    	render 'login'
		  		end
			end

			def logout
				session[:apiuser_id] = nil
				redirect_to dev_login_path, :notice => 'Utloggad'
			end

			def users
				@apiusers = Apiuser.where(is_admin: '0')
			end

			def edit
				@apiuser = Apiuser.find(params[:id])
			end

			def update
				@apiuser = Apiuser.find(params[:id])

				if @apiuser.update(apiuser_params)
		    		redirect_to dev_userslist_path, :notice => 'Användare uppdaterad'
		  		else
		    		render 'edit'
		  		end
			end

			def destroy
		  		@apiuser = Apiuser.find(params[:id])
		  		@apiuser.destroy
		 
		  		redirect_to dev_userslist_path
			end

			private
				def apiuser_params
					params.require(:apiuser).permit(:email, :password, :password_confirmation, :blocked)
				end

			private
				def require_login
					if current_user.nil? then
						redirect_to dev_login_path
					end
				end

			private
				def require_admin
					if current_admin.nil? then
						redirect_to dev_login_path
					end
				end

			def default_format_html
		        request.format = "html"
		    end
		end
	end
end

toerh client/app/controllers/dev/v1/docs_controller.rb
module Dev
	module V1
		class DocsController < BaseController

			layout "docs"
			
			def index
			end
			def resources
			end
			def users
			end
			def tags
			end
			def licenses
			end
			def resourcetypes
			end
			def errors
			end
		end
	end
end

toerh client/app/views/dev/v1/apiusers/account.html.erb
<% content_for :main do %>

<div class="dashboard">

	<h1>Dashboard</h1>

	<h3>Account information</h3>

	<p>
		Email: <%= @email %><br>
		Name: <%= @name %><br>
		Daily count: <%= @count %>
	</p>

	<h3>Access token</h3>

	<span class="highlight"><%= @token %></span>

</div>

<% end %>

toerh client/app/views/dev/v1/apiusers/edit.html.erb
<% content_for :main do %>

<div class="dashboard">

<h1>Edit user</h1>

<%= form_for @apiuser, :url => dev_update_user_path(), method: :patch do |f| %>

	<% if @apiuser.errors.any? %>
        <div class="error-messages">
            <h3>Form is invalid</h3>
            <ul>
                <% for message in @apiuser.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
  
  	<p>
    	<%= f.label :email %><br>
    	<%= f.email_field :email %>
  	</p>

  	<p>
    <%= f.label :blocked %><br>
  		<%= f.check_box :blocked %>
  	</p>
 
  	<p>
    	<%= f.submit %>
  	</p>

<% end %>

<%= link_to 'Back to list', dev_userslist_path %>

</div>

<% end %>

toerh client/app/views/dev/v1/apiusers/login.html.erb
<% content_for :main do %>

  <div class="login">
    <h1>Login</h1>

    <% if flash[:notice] %>
    	<div class="notice">
    		<%= flash[:notice] %>
    	</div>
    <% end %>

    <%= form_tag dev_post_login_path do %>

    	<p>
        	<%= email_field_tag :email, params[:email], :placeholder => "Email" %>
      	</p>
     
      	<p>
        	<%= password_field_tag :password, '', :placeholder => "Password" %>
      	</p>

      	<p>
        	<%= submit_tag 'Login' %>
      	</p>

    <% end %>

    </div>

<% end %>

toerh client/app/views/dev/v1/apiusers/register.html.erb
<% content_for :main do %>
  
  <div class="login">

  <h1>Register</h1>

  <%= form_for(@apiuser, :url => dev_apiusers_path()) do |f| %>
  	<% if @apiuser.errors.any? %>
  		<div class="error-messages">
  			<h3>Form is invalid</h3>
  			<ul>
  				<% for message in @apiuser.errors.full_messages %>
  					<li><%= message %></li>
  				<% end %>
  			</ul>
  		</div>
  	<% end %>

    	<p>
      	<%= f.email_field :email, :placeholder => "Email" %>
    	</p>
   
    	<p>
      	<%= f.password_field :password, :placeholder => "Password" %>
    	</p>

    	<p>
      	<%= f.password_field :password_confirmation, :placeholder => "Password confirmation" %>
    	</p>
   
    	<p>
      	<%= f.submit %>
    	</p>
  <% end %>

  </div>
<% end %>

toerh client/app/views/dev/v1/apiusers/users.html.erb
<% content_for :main do %>

  <div class="dashboard">
    <h1>Api users</h1>

    <table class="clean">
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Access token</th>
        <th>Count</th>
        <th>Is blocked</th>
      </tr>
     
      <% @apiusers.each do |apiuser| %>
        <tr>
          <td><%= apiuser.email %></td>
          <td><%= apiuser.name %></td>
          <td><%= apiuser.access_token %></td>
          <td><%= apiuser.count %></td>
          <td><%= apiuser.blocked %></td>
          <td><%= link_to 'Edit', dev_edit_user_path(apiuser) %></td>
          <td><%= link_to 'Destroy', dev_delete_user_path(apiuser), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

    </div>

<% end %>